### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by info247** [marcelbonnet/redmine_tables#3]
After the commands:
git clone https://github.com/marcelbonnet/redmine_tables.git redmine_tables
sudo bundle exec rake redmine:plugins:migrate RAILS_ENV=production

I receive this error message:

NameError: uninitialized constant RedmineExtensions
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_tables/lib/redmine_custom_workflows/patches/custom_entity_patch.rb:81:in `<top (required)>'

**Comment by marcelbonnet** [comment]
try _bundle install redmine_extensions_

**Comment by info247** [comment]
1 gem installed
bitnami@ip-172-31-47-117:~/apps/redmine/htdocs$ sudo bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NameError: uninitialized constant RedmineExtensions
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_tables/lib/redmine_custom_workflows/patches/custom_entity_patch.rb:81:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_tables/init.rb:44:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:94:in `instance_eval'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:94:in `register'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_tables/init.rb:3:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:187:in `block in load'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:178:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:178:in `load'
/opt/bitnami/apps/redmine/htdocs/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by marcelbonnet** [comment]
Try to isolate the problem removing all plugins, but _redmine_custom_workflows_ . Then:

1.  `bundle install` 
2.  `rake redmine:plugins` 
3. run the web server 

This problem:

> NameError: uninitialized constant RedmineExtensions
> /opt/bitnami/apps/redmine/htdocs/plugins/redmine_tables/lib/redmine_custom_workflows/patches/custom_entity_patch.rb:81:in `<top (required)>'

Seems to be caused by _redmine_custom_workflows_ . Its dependencies should be installed running `bundle install`.

###  Without Custom Workflows

Finally, _redmine_tables_ shall work without _redmine_custom_workflows_ installed.

### Another Test

I had a problem once using _sudo_ . Check if your sudo and redmine server are using the same gem version:

Sudo gem version:
$ sudo gem -v

Then redmine gem:
$ sudo -i
\# gem -v

They must be the same version.

**Comment by info247** [comment]
Thank you. Problem resolved.

**Comment by info247** [comment]
Installation problem continues, even on a completely new Redmine instance.
